### ISSUE TITLE
Shade the correct NBT API artifact

### ISSUE THREAD

**Issue by iGabyTM** [yakovliam-com/spacechat#28]
You are currently implementing `item-nbt-api-plugin` instead of the right artifact, which breaks other plugins that use NBT API. See this https://github.com/tr7zw/Item-NBT-API/wiki/Using-Maven#option-2-shading-the-nbt-api-into-your-plugin, thanks.

**Comment by yakovliam** [comment]
A pull request would have been appreciated, but instead, I've just removed all references. Thanks for the report!
